- DESCRIPTION
- R/cancensus.R
This makes use of `requireNamespace()` to check if the fast and reliable `readr` package is available, replacing the commented-out code left over from an older version. It also moves `readr` to the Suggests section, since its use is clearly optional. `readr::read_csv` should be available in all versions of the package, so there is no need to specify one.
> Optionally use readr's read_csv if it is available.

- DESCRIPTION
- R/cancensus.R
- man/cancensus.load.Rd
- man/cancensus.load_data.Rd
- man/cancensus.load_geo.Rd
This PR reflects the need to move both `sf` and `rgdal` to the Suggests section of the `DESCRIPTION` file, and ensure that one of them is present when requesting geo data, but that users can opt in to either the `sf` or `sp` paradigms without installing the packages needed for the other. This also cleans up later code, and removes the call to `install.package()`, since there's no need for it now.
I've also taken the liberty of amalgamating the `format` and `geo` options into a single paramter. Users can pass `NA` to avoid returning spatial data. Since this is a breaking change, I'll need to check existing snippets and vignettes to accomodate the change.
(The commits also contain these descriptions.)
> Cean up and clarify the geo format parameters

- R/cancensus.R
The label option assumes that the format is "sp" and breaks when using "sf". This is a quick-fix to address that. We might want to move the code up and perform it on the "dat" object for cleaner handling.
> quickfix to labels with sf format

- R/cancensus.R
- man/cancensus.load.Rd
- man/cancensus.load_data.Rd
- man/cancensus.load_geo.Rd
As discussed in #27. This is a quick implementation that does validation on the client side, and recycles this validation for the `levels` parameter in the process.
Documentation and examples will need to be updated, since this is a breaking API change.
> Change the regions parameter to a named list

- R/cancensus.R
This is a simple quality-of-life addition. If the user has `httr.show_progress` disabled, there's no visual indication that we're reading from the network or the local data cache. This PR adds a message to resolve this.
> Notify the user when reading data from the local cache

- R/cancensus.R
As mentioned in #17, there's not much need for the `set_api_key()` function anymore, so this PR marks it as depreciated, with a helpful migration message pointing users towards `options()` and `Sys.setenv()` instead.
This also changes the text of the errors generated when API keys are missing.
> Depreciate set_api_key()

- R/cancensus.R
- man/cancensus.list_vectors.Rd
Quickfix to add the 'add' column into the select and implement basic client side caching of the vector list.
> add the 'add' column to the select and cache result of vector list

- R/cancensus.R
This PR actually fixes a few issues. It should resolve the "missing file" errors mentioned in #47 and allow us to close that issue. It also makes `list_vectors()` use the same caching approach as `list_regions()` and `list_datasets()`. And finally, it adds a warning to these functions when a user's cache is more than a day old, which should address concerns raised in #50.
> Add cache timeouts

- R/cancensus.R
This should be the final piece of resolving #62. This commit adds an option allowing more control over the caching behaviour. For instance, the old local approach can be recovered with
```r
options(cancensus.cache_path = "./data_cache")
```
The default, caching in the package internals, remains in place.
This option is not yet documented anywhere.
> Add a `cancensus.cache_path` option

- R/cancensus.R
- README.md
As in discussed in #73 
* Set default level for geography to be NA with options to explicitly add census geography in sf or sp form
* Remove `get_census_data()` functionality as it's duplicated by `get_census()`
* Remove mentions of `get_census_data()`
> Change default geo format behaviour

- .travis.yml
- vignettes/Working-with-cancensus.Rmd
- vignettes/bargraph.Rmd
- vignettes/cancensus-demo.Rmd
- vignettes/dot_density_example.Rmd
In order for this to actually work with API requests, we'll need to add an API token in the environment variable `CM_API_KEY` in the Travis CI instance. Explanation for doing that (which requires control of the repository) can be found [here](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings). I'd like to make sure this works before merging.
This would address #72.
> Add a configuration file for Travis CI

- R/cancensus.R
- man/get_census.Rd
This is available for all other functions, so it's nice to have it on the main one. This should also reduce some of the noisy output in vignettes.
I've also fixed some unsuppressed output in `list_census_vectors()`.
> Add a quiet parameter to get_census()

- R/cancensus.R
Reverts mountainMath/cancensus#80
Ran into issues, not sure how to resolve them. Tried running the cancensus-demo vignette, loading `sf` data from cache. The join with the data table failed. One way to fix this was to first convert data to `sp` and then back to `sf`, but this process seemed to lose the crs data.
How about we go back to storing the geojson for now and just parsing that with the appropriate methods? Might be slower and use more disk space, but much more robust.
> Revert "Convert cached geo data from sp to/from sf when necessary"

- R/cancensus.R
Quick fix to update the documentation for the parameter `labels`. 
Discussed in #86
> Fix old reference in labels parameter in get_census

- R/cancensus.R
- man/list_census_regions.Rd
I added the "parent" regions to the place name data API, this pull request makes sure they are available in `cancensus` in the `list_regions` call.
This enables more pinpointed region searches, for example "give me the 4 largest municipalities in Metro Vancouver" would be
```
cma_id <- list_census_regions('CA16') %>% filter(level=='CMA', name=='Vancouver') %>% pull("region")
csds <- list_census_regions('CA16', use_cache=TRUE) %>% 
filter(level=='CSD', CMA_UID==cma_id) %>%
top_n(4,pop)
```
> parse parent region geo_uids

- vignettes/dot_density_example.Rmd
The errors in compiling the package was due to this vignette requiring libraries that are not dependencies to the overall package. Specifically, it's ggthemes, which also requires mapproj. I don't think it's necessary for the visual intended in the vignette and I cut it out, and made a small graphical change to the legend as well as it was buggy when testing otherwise.
> Fix vignette so it can compile without additional packages

- R/cancensus.R
When an empty vector list parameter is passed to `child_census_vectors` function, it raises an error because `dataset` attribute is `NULL` and a call to `list_census_vectors` fails because of invalid parameter.
The following example illustrates this:
```
search_census_vectors(
"no results for me",
"CA16,
type = "Total",
use_cache = TRUE
) %>%
child_census_vectors(leaves_only = FALSE)
```
While in the example above this can be worked around by checking if number of rows returned by `search_census_vectors` is greater than 0, it would break the piping.
This pull request fixes this issue by making sure `child_census_vectors` returns an empty list, which is valid because an empty vectors list doesn't have any child nodes.
> Fix an error when empty vector list is passed to child_census_vectors.

- R/cancensus.R
- man/list_census_vectors.Rd
This switches the default parameter to `QUIET` for list_census_vectors. This also affects downstream functions that also use list_census_vectors like search_census_vectors. In practice, I found that it produces too many messages and isn't that useful.
> Make list_census_vectors quiet by default

- R/cancensus.R
This change ensure that read.csv connects to text properly if readr is not loaded. This addresses the bug in issue #110.
> Ensure read.csv works

- R/cancensus.R
Ensures that `sf` format results have class sf, so long as `sf` is available even if it is not loaded.
> Sf require fix

- R/vector_discovery.R
Fixes bugs in `find_census_vectors()` flagged in #150. 
```
find_census_vectors("full year, full time", "CA16",
type = c("male", "female"),
query_type = "exact")
vector     type   label              details                                                           
<chr>      <fct>  <chr>              <chr>                                                             
1 v_CA16_56… Male   Worked full year,… 25% Data; Work; Work Activity; Total population aged 15 years and…
2 v_CA16_56… Female Worked full year,… 25% Data; Work; Work Activity; Total population aged 15 years and…
```
```
find_census_vectors("part year and/or part time", 
"CA16",
type = c("male", "female"),
query_type = "exact")
vector    type   label                  details …
```
> Fix bug when requesting multiple variable types at once

- R/cancensus.R
- R/intersect_geometry.R
- vignettes/cancensus.Rmd
change error messages and vignette to refer to  renamed set_cancensus_api_key
The error message confused me, so it'll confuse someone else!
> change error messages and vignette to refer to  renamed set_cancensus_api_key
